language: php

php:
    - 5.3
    
install: composer install -v --dev
     
script:
    - mkdir -p build/logs
    - vendor/bin/phpunit --colors --configuration phpunit.xml --bootstrap unittests/phpunit.php --coverage-clover build/logs/clover.xml unittests