language: php

php:
    - 5.3
    
install: composer install -v --dev
     
script:
    - mkdir build/logs
    - vendor/bin/phpunit --colors --bootstrap unittests/php-unit.php unittests --coverage-clover build/logs/clover.xml