<?php
namespace Flikore\Validator;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2014-03-02 at 18:40:41.
 */
class ExactValueValidatorTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ExactValueValidator
     */
    //protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        //$this->object = new ExactValueValidator;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
    
    public function testSuccess()
    {
        $v = new ExactValueValidator(5);
        $this->assertTrue($v->validate(5));
        $this->assertTrue($v->validate(null));
    }
    
    public function testFailure()
    {
        $v = new ExactValueValidator(5);
        $this->assertFalse($v->validate(7));
        $this->assertFalse($v->validate(2));
    }
    
    /**
     * @expectedException \InvalidArgumentException
     */
    public function testInvalidValueArgument()
    {
        $v = new ExactValueValidator('aa');
    }
}
