<?php

namespace Flikore\Validator;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2014-03-03 at 01:40:03.
 */
class InstanceOfValidatorTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @expectedException \InvalidArgumentException
     */
    public function testInvalidIntegerArgument()
    {
        $v = new InstanceOfValidator(123);
    }

    /**
     * @expectedException \InvalidArgumentException
     * @covers Flikore\Validator\InstanceOfValidator::__construct
     */
    public function testInvalidNullArgument()
    {
        $v = new InstanceOfValidator(null);
    }

    /**
     * @covers Flikore\Validator\InstanceOfValidator::doValidate
     */
    public function testSuccessClassName()
    {
        $a = new \BadFunctionCallException();

        $v = new InstanceOfValidator('BadFunctionCallException');

        $this->assertTrue($v->validate($a));
    }

    public function testSuccessObject()
    {
        $a = new \BadFunctionCallException();

        $v = new InstanceOfValidator($a);

        $this->assertTrue($v->validate($a));
    }

    public function testFailClassName()
    {
        $a = new \BadFunctionCallException();

        $v = new InstanceOfValidator('InvalidArgumentException');

        $this->assertFalse($v->validate($a));
    }

    public function testFailObject()
    {
        $a = new \BadFunctionCallException();
        $b = new \InvalidArgumentException();

        $v = new InstanceOfValidator($b);

        $this->assertFalse($v->validate($a));
    }

    public function testSuccessEmpty()
    {
        $a = new \BadFunctionCallException();

        $v = new InstanceOfValidator($a);

        $this->assertTrue($v->validate(null));
    }

}
