<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2014-03-02 at 02:13:34.
 */
class SplClassLoaderTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var SplClassLoader
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new SplClassLoader;
    }

    

}
